/*
 * This source file was generated by the Gradle 'init' task
 */
package weatherapp;

public class App {

    public static void main(String[] args) {
        String city = "springfield";
        Reader r = new Reader(city);
        try{
        r.fetchApiData(r.getGeoCodingApiURL());
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    
    }

    String getGreeting() {
        return "Hi";
    }

    
}



/*              MY FIRST WEATHER APP
* 
    1) the intention of the app is to check the current weather in a specific location
    2) Initially will be a console app that will ask for a user for a city where they want to know the weather 
    3) the system will retrieve the matches to the query and if more than one result comes up, enumerate the results and ask the usrr for what is the city that they were trying to find
    4) display the city, state and country with the current weather.  


    -> usel will provide a string, then with that string i have to find first for matches 
*/

/*      To do
 * 
 * now that i have translated the JSON to objects, im having a list of cities. 
 * -> Present the results to the user with an index and have the use select what city theyre interested in 
 * -> when the targte city has been selected, get the city from that index and with the longitude and latitude adn create a geolocation.
 * -> once i have the GeoLocation i will do a GET request from the WeatherAPI for that specific location.
 * -> once i have a response
 */
